version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketplaceDB
    ports:
      - '5430:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
